In [ ]:
import torch as th

a = th.tensor([1, 2, 3,4,5,6,7,8,9,10])

b = (th.rand(1, 10) > 0.5).squeeze()

c = (th.rand(1, 10)*10).squeeze()

n_points = a.size(0)


# create a tensor with a b c as columns

X = th.stack([a, b, c], dim=1)

# make X contiguous
X = X.contiguous()

print(X)

bins = th.tensor([0, 3, 6, 9, 10])

n_areas = bins.size(0)

areas = th.bucketize(X[:, 2], bins)

print(areas)

area_mask = th.zeros((n_points, n_areas), dtype=th.bool, device=X.device)
area_mask[th.arange(n_points), areas] = 1




tensor([[1.0000e+00, 1.0000e+00, 4.0656e+00],
        [2.0000e+00, 0.0000e+00, 7.8408e+00],
        [3.0000e+00, 1.0000e+00, 2.4220e+00],
        [4.0000e+00, 1.0000e+00, 9.8088e+00],
        [5.0000e+00, 0.0000e+00, 4.9249e-01],
        [6.0000e+00, 0.0000e+00, 1.0096e+00],
        [7.0000e+00, 1.0000e+00, 3.8957e+00],
        [8.0000e+00, 1.0000e+00, 6.6876e-03],
        [9.0000e+00, 0.0000e+00, 2.4193e+00],
        [1.0000e+01, 1.0000e+00, 5.8027e+00]])
tensor([2, 3, 1, 4, 1, 1, 2, 1, 1, 2])


In [ ]:
# print(area_mask)
# apply validity mask to columns of area_mask
validity_mask = X[:, 1].bool()
area_mask = area_mask & validity_mask.unsqueeze(1)


print(area_mask)





tensor([[False, False,  True, False, False],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False,  True, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False]])


In [13]:
# cumsum per column

area_counts = area_mask.cumsum(dim=0)
print(area_counts)

tensor([[0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 1, 0, 0],
        [0, 1, 1, 0, 1],
        [0, 1, 1, 0, 1],
        [0, 1, 1, 0, 1],
        [0, 1, 2, 0, 1],
        [0, 2, 2, 0, 1],
        [0, 2, 2, 0, 1],
        [0, 2, 3, 0, 1]])


In [8]:
# or all columns

retain_mask = area_mask.any(dim=1).squeeze()

print(retain_mask)  

E = X[retain_mask]

print(E)

tensor([ True, False,  True,  True, False, False,  True,  True, False,  True])
tensor([[1.0000e+00, 1.0000e+00, 4.0656e+00],
        [3.0000e+00, 1.0000e+00, 2.4220e+00],
        [4.0000e+00, 1.0000e+00, 9.8088e+00],
        [7.0000e+00, 1.0000e+00, 3.8957e+00],
        [8.0000e+00, 1.0000e+00, 6.6876e-03],
        [1.0000e+01, 1.0000e+00, 5.8027e+00]])
